# ----- Eigen Decomposition -----

## *From Scratch*

In [29]:
import numpy as np

In [30]:
# ----- Define Matrix -----
A = np.array([[4, -2],
              [1, 1]], dtype=float)

In [31]:
# ----- Step 1: Characteristic Equation |A - λI| = 0 -----
# (λ^2 - 5λ + 6 = 0)
coeff = [1, -5, 6]  # From manual expansion or np.poly()

In [32]:
# ----- Step 2: Solve for Eigenvalues -----
eigenvalues = np.roots(coeff)

In [33]:
# ----- Display -----
print("Eigenvalues:")
print(np.round(eigenvalues, 2))

Eigenvalues:
[3. 2.]


In [34]:
# ----- Step 3: Find Eigenvectors for each Eigenvalue -----
eigenvectors = []
for λ in eigenvalues:
    M = A - λ * np.eye(2)
    # Solve (A - λI)v = 0  --> find vector v
    # Use np.linalg.svd to get null space vector
    U, S, Vt = np.linalg.svd(M)
    null_space_vector = Vt[-1]  # last row gives vector in null space
    eigenvectors.append(null_space_vector / np.linalg.norm(null_space_vector))

eigenvectors = np.column_stack(eigenvectors)  # combine into matrix P

In [35]:
print("\nEigenvectors (P):")
print(np.round(eigenvectors, 2))


Eigenvectors (P):
[[0.89 0.71]
 [0.45 0.71]]


In [36]:
# ----- Step 4: Diagonal Matrix -----
D = np.diag(eigenvalues)

In [37]:
print("\nDiagonal Matrix (D):")
print(np.round(D, 2))


Diagonal Matrix (D):
[[3. 0.]
 [0. 2.]]


In [38]:
# ----- Step 5: Verify A = P * D * P⁻¹ -----
A_reconstructed = eigenvectors @ D @ np.linalg.inv(eigenvectors)

In [39]:
print("\nReconstructed A:")
print(np.round(A_reconstructed, 2))


Reconstructed A:
[[ 4. -2.]
 [ 1.  1.]]


## *Using Libraries*

In [40]:
import numpy as np

In [41]:
# ----- Define Matrix -----
A = np.array([[4, -2],
              [1, 1]])

In [42]:
print("Matrix A:")
print(A)

Matrix A:
[[ 4 -2]
 [ 1  1]]


In [43]:
# ----- Eigenvalues & Eigenvectors -----
eigenvalues, eigenvectors = np.linalg.eig(A)

In [44]:
print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors (P):")
print(eigenvectors)


Eigenvalues:
[3. 2.]

Eigenvectors (P):
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [45]:
# ----- Form the Diagonal Matrix (D) -----
D = np.diag(eigenvalues)

In [46]:
print("\nDiagonal Matrix (D):")
print(D)


Diagonal Matrix (D):
[[3. 0.]
 [0. 2.]]


In [47]:
# ----- Verify A = P * D * P⁻¹ -----
A_reconstructed = eigenvectors @ D @ np.linalg.inv(eigenvectors)

In [49]:
print("\nReconstructed A (P * D * P⁻¹):")
print(np.round(A_reconstructed, 2))


Reconstructed A (P * D * P⁻¹):
[[ 4. -2.]
 [ 1.  1.]]
