# ----- Matrix Functions -----

## *From Scratch*

In [14]:
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

In [15]:
def display(matrix):
    for row in matrix:
        print(row)

In [16]:
print("Matrix A:")
display(A)

Matrix A:
[1, 2]
[3, 4]


In [17]:
print("\nMatrix B:")
display(B)


Matrix B:
[5, 6]
[7, 8]


In [18]:
def add(A, B):
    return [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

In [19]:
print("\nA + B:")
display(add(A, B))


A + B:
[6, 8]
[10, 12]


In [20]:
def subtract(A, B):
    return [[A[i][j] - B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

In [21]:
print("\nA - B:")
display(subtract(A, B))


A - B:
[-4, -4]
[-4, -4]


In [22]:
def multiply(A, B):
    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(B[0])):
            val = 0
            for k in range(len(A[0])):
                val += A[i][k] * B[k][j]
            row.append(val)
        result.append(row)
    return result

In [23]:
print("\nA * B:")
display(multiply(A, B))


A * B:
[19, 22]
[43, 50]


In [24]:
def transpose(A):
    return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]

In [25]:
print("\nTranspose of A:")
display(transpose(A))


Transpose of A:
[1, 3]
[2, 4]


In [26]:
def scalar_multiply(A, scalar):
    return [[elem * scalar for elem in row] for row in A]

In [27]:
print("\nA multiplied by scalar 3:")
display(scalar_multiply(A, 3))


A multiplied by scalar 3:
[3, 6]
[9, 12]


In [28]:
def identity(size):
    return [[1 if i == j else 0 for j in range(size)] for i in range(size)]

In [29]:
print("\nIdentity Matrix (3x3):")
display(identity(3))


Identity Matrix (3x3):
[1, 0, 0]
[0, 1, 0]
[0, 0, 1]


In [30]:
def determinant(A):
    if len(A) == 1:
        return A[0][0]
    if len(A) == 2:
        return A[0][0]*A[1][1] - A[0][1]*A[1][0]
    det = 0
    for c in range(len(A)):
        minor = [row[:c] + row[c+1:] for row in A[1:]]
        det += ((-1)**c) * A[0][c] * determinant(minor)
    return det

In [31]:
print("\nDeterminant of A:", determinant(A))


Determinant of A: -2


In [32]:
# ----- Cofactor Matrix -----
def cofactor_matrix(A):
    cofactors = []
    for r in range(len(A)):
        row = []
        for c in range(len(A)):
            minor = [A[i][:c] + A[i][c+1:] for i in range(len(A)) if i != r]
            row.append(((-1)**(r+c)) * determinant(minor))
        cofactors.append(row)
    return cofactors

In [33]:
# ----- Inverse -----
def inverse(A):
    det = determinant(A)
    if det == 0:
        raise ValueError("Matrix is not invertible (determinant = 0).")
    
    cof = cofactor_matrix(A)
    adjoint = transpose(cof)
    inv = [[adjoint[i][j] / det for j in range(len(A))] for i in range(len(A))]
    return inv

In [34]:
# ----- Display -----
def display(matrix):
    for row in matrix:
        print([round(x, 2) for x in row])

In [35]:
# ----- Example -----
A = [[4, 7], [2, 6]]

print("Matrix A:")
display(A)

print("\nInverse of A:")
display(inverse(A))

Matrix A:
[4, 7]
[2, 6]

Inverse of A:
[0.6, -0.7]
[-0.2, 0.4]


## *Using Libraries*

In [36]:
import numpy as np


In [37]:
# ----- Define Matrices -----
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [38]:
# ----- Display -----
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]


In [39]:
# ----- Addition -----
print("\nA + B:\n", np.add(A, B))


A + B:
 [[ 6  8]
 [10 12]]


In [40]:
# ----- Subtraction -----
print("\nA - B:\n", np.subtract(A, B))


A - B:
 [[-4 -4]
 [-4 -4]]


In [41]:
# ----- Multiplication (Matrix Product) -----
print("\nA * B (Matrix Multiplication):\n", np.dot(A, B))


A * B (Matrix Multiplication):
 [[19 22]
 [43 50]]


In [42]:
# ----- Transpose -----
print("\nTranspose of A:\n", np.transpose(A))


Transpose of A:
 [[1 3]
 [2 4]]


In [43]:
# ----- Scalar Multiplication -----
print("\nA multiplied by scalar 3:\n", 3 * A)


A multiplied by scalar 3:
 [[ 3  6]
 [ 9 12]]


In [44]:
# ----- Identity Matrix -----
print("\nIdentity Matrix (3x3):\n", np.identity(3))


Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
# ----- Determinant -----
print("\nDeterminant of A:", np.linalg.det(A))


Determinant of A: -2.0000000000000004


In [46]:
# ----- Inverse -----
try:
    inv_A = np.linalg.inv(A)
    print("\nInverse of A:\n", np.round(inv_A, 2))
except np.linalg.LinAlgError:
    print("\nMatrix A is not invertible (determinant = 0).")


Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
