# ----- Rank of a Matrix -----

## *From Scratch (Row Echelon Form Method)*

In [1]:
import numpy as np

In [2]:
def rank_from_scratch(A):
    A = A.astype(float)
    rows, cols = A.shape
    rank = 0

    for r in range(rows):
        if A[r][r] != 0:
            # Make pivot 1
            A[r] = A[r] / A[r][r]
            for i in range(rows):
                if i != r:
                    A[i] = A[i] - A[i][r] * A[r]
        else:
            # Swap with a lower row that has a non-zero pivot
            for i in range(r+1, rows):
                if A[i][r] != 0:
                    A[[r, i]] = A[[i, r]]
                    break
    # Count non-zero rows
    for row in A:
        if not np.allclose(row, 0):
            rank += 1
    return rank

In [4]:
# ----- Example -----
A = np.array([[2, 4, 1],
              [6, 12, 3],
              [1, 2, 0]], dtype=float)

In [5]:
print("Matrix A:")
print(A)

Matrix A:
[[ 2.  4.  1.]
 [ 6. 12.  3.]
 [ 1.  2.  0.]]


In [7]:
print("\nRank of A:", rank_from_scratch(A))


Rank of A: 2


## *Using Libraries*

In [8]:
import numpy as np

In [9]:
# ----- Define Matrix -----
A = np.array([[2, 4, 1],
              [6, 12, 3],
              [1, 2, 0]])

In [10]:
print("Matrix A:")
print(A)

Matrix A:
[[ 2  4  1]
 [ 6 12  3]
 [ 1  2  0]]


In [11]:
# ----- Find Rank -----
rank = np.linalg.matrix_rank(A)

In [12]:
print("\nRank of Matrix A:", rank)


Rank of Matrix A: 2
